# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 自我治疗的精神病人
email: zhb19941010@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  积极康复中
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.Ricordo.github.io" # the base hostname & protocol for your site
github_username:  Ricordo

# Build settings
markdown: kramdown
